## Docker Model Runner refer README.md##
# gpt-oss:20b, deepseek-coder-v2:latest
#spring.ai.ollama.chat.options.model=qwen3:8b

spring.ai.model.chat=openai
spring.ai.openai.base-url=http://localhost:12434/engines/
# this i had pulled in docker desktop
spring.ai.openai.chat.options.model=ai/smollm2:latest
spring.ai.openai.api-key=dummy
logging.level.org.springframework.ai.chat.client.advisor=DEBUG