spring.ai.model.chat=openai
spring.ai.openai.base-url=http://localhost:12434/engines/
# this one I had pulled in docker desktop
spring.ai.openai.chat.options.model=ai/smollm2:latest
spring.ai.openai.api-key=dummy

logging.level.org.springframework.ai.chat.client.advisor=DEBUG