## OpenRouter##
spring.ai.openai.base-url=https://openrouter.ai
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.completions-path=/api/v1/chat/completions
#As we cant use free deepseek directly- but with this openrouter, we can connect as below free
chat-model=deepseek/deepseek-r1-0528:free
spring.ai.openai.chat.options.model=${chat-model}