## Google Gemini OpenAI Compat Mode ##
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.api-key=${GEMINI_API_KEY}
## play with many versions, sometimes it won't connect even the key is correct
spring.ai.openai.chat.options.model=gemini-2.5-flash