spring.application.name=01-chat-openai
spring.main.web-application-type=servlet
server.port=8080
## set this environment powershell
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=https://api.openai.com
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature = 0
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
